-- All PKs are auto generated by the database

-- Metals Seed Data
INSERT INTO Metals (metalType, metalBundleSize, lastOrdered, Classificationid, bundlesOnHand)
VALUES
('Titanium', 20, '2019-07-07 23:18:22.3333333', 2, 12),
('Gold', 12, '2022-05-07 23:18:22.5533333', 1, 4),
('Lead', 100, '2021-04-17 23:18:21.5332133', 2, 51),
('Copper', 24, '2022-04-17 21:12:21.4433333', 2, 75),
('Tin', 100,'2022-03-21 13:18:22.5533100' ,2, 100),
('Iron', 125, '2022-05-05 12:00:12.5533344', 2, 45),
('Brass', 15, '2021-12-01 11:12:01.3232333', 1, 32),
('Silver', 6, '2022-05-07 23:18:22.5533333', 1, 12),
('Aluminum', 10, '2022-01-07 13:18:19.2133333', 3, 109);

-- Classification Seed Data
INSERT INTO Classifications (classificationTitle, classificationDescription)
VALUES
('Precious Metals', 'Non-Construction Based Metals Used In Decorative Wares'),
('Construction Metals', 'Hardened Metals Used In Costruction Projects'),
('Manufacturing Metals', 'Metals Used In Manufacturing Household Products');

-- Vendors Seed Data
INSERT INTO Vendors (vendorName, vendorCity, vendorStateTerritory, vendorCountry)
VALUES
('Starway Refineries', 'Toronto', 'Ontario', 'Canada'),
('Michellin Masters', 'Morgantown', 'West Virginia', 'United States'),
('Elemental Direct', 'Tampa', 'Florida', 'United States'),
('San Diego Refining Company', 'San Diego', 'California', 'United States');

-- Orders Seed Data
INSERT INTO Orders (orderTime, metalId, orderBatchQuantity, vendorId)
VALUES
('2022-05-05 12:00:12.5533344', 4, 70, 1),
('2022-03-21 13:18:22.5533100', 3, 50, 1);
